# 1. PERSISTENCE: Create "claims" for our stateful data.
# Minikube will automatically provide storage for these.
# 2. DATABASE: Deploy MongoDB
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # This is the hostname our Spring App will use
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP # INTERNAL only. Not exposed outside the cluster.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi"   # Minimum RAM to start
              cpu: "100m"       # 10% of a CPU core
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"   # Maximum RAM allowed
              cpu: "500m"       # 50% of a CPU core
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

# 3. APPLICATION: Deploy our Spring Boot App
---
apiVersion: v1
kind: Service
metadata:
  name: solid-app-service
spec:
  selector:
    app: solid-app
  ports:
    - port: 8181
      targetPort: 8080
  type: LoadBalancer # Expose this service outside the cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solid-app-deployment
spec:
  replicas: 1 # Let's run 2 instances for high availability!
  selector:
    matchLabels:
      app: solid-app
  template:
    metadata:
      labels:
        app: solid-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: solid-app
          image: solid-project:0.0.1 # The image we will build locally
          imagePullPolicy: Never # IMPORTANT: Tells K8s to use the local image
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 10
                # --- ADD THE READINESS PROBE ---
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness # The endpoint Spring provides
              port: 8080
            initialDelaySeconds: 30             # Wait 30s before first check
            timeoutSeconds: 5                   # Max time allowed per check
            periodSeconds: 10                   # Check every 10 seconds
            failureThreshold: 10                 # Fail after 3 consecutive failures
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "1000m"      # Allow full core burst during startup
              ephemeral-storage: "2Gi"
          env: # Set environment variables
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo-service:27017/solid-db"

# 4. TOOLING: Deploy SonarQube
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  selector:
    app: sonar
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      automountServiceAccountToken: false
      containers:
        - name: sonar
          image: sonarqube:community
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "1Gi"     # Sonar needs a lot to start
              cpu: "500m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "2Gi"     # Hard cap to stop it freezing your PC
              cpu: "1500m"
              ephemeral-storage: "2Gi"
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-extensions     # Mount Plugins
              mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data-pvc
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions-pvc # Matches infra-storage.yaml
  selector:
    matchLabels:
      app: sonar

# 5. TOOLING: Deploy Jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - name: http-web
      port: 8081
      targetPort: 8080
    - name: agent-jnlp
      port: 50001
      targetPort: 50000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      automountServiceAccountToken: false
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home # Critical Path
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc      # Matches infra-storage.yaml
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
  selector:
    matchLabels:
      app: jenkins